cfn-lint-serverless/pyproject.toml
cfn-lint-serverless/tests/test_templates.py
tflint-ruleset-aws-serverless/main.go

fix: test that rule ID is not matched on pass templates

---

.github/labeler.yml
.github/release-drafter.yml
.github/workflows/release-drafter.yml

*Description of changes:* add release-drafter for automated release draft generation.

chore: add release drafter

---

README.md

Signed-off-by: heitorlessa <lessa@amazon.co.uk>
This adds additional explanation and navigation to `cfn-lint` and `tflint`.

docs: expand usage guide into anchors

---

CONTRIBUTING.md
Makefile
README.md
docs/tflint.md
examples/tflint/.tflint.hcl
tflint-ruleset-aws-serverless/go.mod
tflint-ruleset-aws-serverless/main.go

*Description of changes:* Change all references of `aws-samples` to `awslabs`.

chore: move to awslabs

---

.github/workflows/publish.yml
Makefile
examples/tflint/Makefile
tflint-ruleset-aws-serverless/.goreleaser.yml
tflint-ruleset-aws-serverless/main.go
tflint-ruleset-aws-serverless/rules/provider.go

* Add list of rules in `rules/provider.go` file
* Add goreleaser to automatically add binaries to releases
* Automatically compile the plugin when running the tflint example

chore: improvements for the tflint plugin

---

docs/rules/index.md
docs/rules/lambda.md
tflint-ruleset-aws-serverless/Makefile
tflint-ruleset-aws-serverless/rules/aws_lambda_event_source_mapping_failure_destination.go
tflint-ruleset-aws-serverless/rules/aws_lambda_event_source_mapping_failure_destination_test.go
tflint-ruleset-aws-serverless/rules/provider.go
tflint-ruleset-aws-serverless/templates/rule.go.tmpl
tflint-ruleset-aws-serverless/templates/rule_test.go.tmpl

Add __Lambda EventSourceMapping Failure Destination__ rule for Terraform.

feat: EventSourceMapping Failure Destination for tflint

---

docs/rules/index.md
docs/rules/step_functions.md
tflint-ruleset-aws-serverless/rules/aws_sfn_state_machine_tracing.go
tflint-ruleset-aws-serverless/rules/aws_sfn_state_machine_tracing_test.go

*Description of changes:* Add Step Functions Tracing rule for tflint

feat: add Step Functions Tracing rule for tflint

---

tflint-ruleset-aws-serverless/.goreleaser.yml

chore: update goreleaser to match tflint 0.29 requirements

---

docs/cfn-lint.md
docs/tflint.md

*Issue #, if available:* https://github.com/awslabs/serverless-rules/issues/34
Add sections in the documentation for ignoring rules with `cfn-lint` and `tflint`.

docs: add section on ignoring rules

---

README.md
docs/contributing/create_rule.md
docs/index.md
docs/rules/api_gateway.md
docs/rules/appsync.md
docs/rules/eventbridge.md
docs/rules/index.md
docs/rules/lambda.md
docs/rules/step_functions.md
docs/tflint.md

Fix grammatical issues in the documentation.

docs: grammatical improvements

---

docs/rules/eventbridge.md
docs/rules/index.md
tflint-ruleset-aws-serverless/rules/aws_cloudwatch_event_target_no_dlq.go
tflint-ruleset-aws-serverless/rules/aws_cloudwatch_event_target_no_dlq_test.go

Parity with `cfn-lint` for the EventBridge No DLQ rule.

feat(tflint): rule for EventBridge Rule No DLQ

---

cfn-lint-serverless/cfn_lint_serverless/rules/__init__.py
cfn-lint-serverless/cfn_lint_serverless/rules/sqs.py
cfn-lint-serverless/tests/templates/es6000.fail.yaml
cfn-lint-serverless/tests/templates/es6000.pass.yaml
docs/rules/index.md
docs/rules/sqs.md
mkdocs.yml
tflint-ruleset-aws-serverless/rules/aws_sqs_queue_redrive_policy.go
tflint-ruleset-aws-serverless/rules/aws_sqs_queue_redrive_policy_test.go
tflint-ruleset-aws-serverless/rules/provider.go

New rule to check if SQS queue has a redrive policy configured.

feat: SQS No Redrive Policy

---

cfn-lint-serverless/cfn_lint_serverless/rules/__init__.py
cfn-lint-serverless/cfn_lint_serverless/rules/sns.py
cfn-lint-serverless/tests/templates/es7000.fail.yaml
cfn-lint-serverless/tests/templates/es7000.pass.yaml
docs/rules/index.md
docs/rules/sns.md
docs/rules/sqs.md
mkdocs.yml
tflint-ruleset-aws-serverless/rules/aws_sns_topic_subscription_redrive_policy.go
tflint-ruleset-aws-serverless/rules/aws_sns_topic_subscription_redrive_policy_test.go
tflint-ruleset-aws-serverless/rules/provider.go

Add a new rule that checks if SNS subscriptions have a redrive policy configured.

feat: SNS redrive policy rule

---

docs/index.md

*Issue #, if available:* https://github.com/awslabs/serverless-rules/issues/42
Add an FAQ section in the documentation. It only contains 2 questions at the moment, but we can add more as they come.

docs: add FAQ

---

docs/cfn-lint.md
docs/tflint.md

Add instructions on how to use `cfn-lint` and `tflint` with GitLab.

docs: add GitLab instructions

---

cfn-lint-serverless/cfn_lint_serverless/rules/api_gateway.py
cfn-lint-serverless/cfn_lint_serverless/rules/appsync.py
cfn-lint-serverless/cfn_lint_serverless/rules/eventbridge.py
cfn-lint-serverless/cfn_lint_serverless/rules/lambda_.py
cfn-lint-serverless/cfn_lint_serverless/rules/sns.py
cfn-lint-serverless/cfn_lint_serverless/rules/sqs.py
cfn-lint-serverless/cfn_lint_serverless/rules/step_functions.py

Add links to the documentation from all the rules for  cfn-lint` and `tflint`.

feat: add URL references to rules

---

docs/rules/index.md

docs: remove non-implemented rules from index

---

docs/rules/api_gateway/default_throttling.md

Fixed typo in default_throttling.md

---

docs/tflint.md

wrong JUnit report filename
used filename from line 261 instead

correct filename, instead of cfn-lint one

---

README.md

This PR updates the project version from 0.3.2 to 0.3.3 in the README.md file. This ensures the documentation correctly references the latest version of the plugin for users.
Changes
Updated version number in .tflint.hcl configuration example from 0.3.2 to 0.3.3

fix: updated release version in readme

---

README.md
docs/tflint.md
examples/tflint/.tflint.hcl

Updated addition versions for relase check validation in docs and samples

chore(ci): fix release version
